version: '3.8'

services:
  spark-jupyter:
    image: spark-jupyter
    build:
      context: .
      target: jupyter-notebook
    container_name: spark-jupyter
    volumes:
      - ./notebooks:/opt/notebooks
      - spark-logs:/opt/spark/spark-events
    ports:
      - '8888:8888'
    labels:
      - "com.example.group=spark"

  spark-master:
    container_name: spark-master
    build:
      context: .
      target: pyspark
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
      - ./notebooks:/opt/notebooks
    env_file:
      - .env.spark
    ports:
      - '4040:4040'
      - '9090:8080'
      - '7077:7077'
#      - '15000:15000'
    labels:
      - "com.example.group=spark"


  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    labels:
      - "com.example.group=spark"

  spark-worker:
    image: spark-image
    # container_name: spark-worker
    entrypoint: ['./entrypoint.sh', 'worker']
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
      - ./notebooks:/opt/notebooks
    ports:
      - "8000-8020:81"
    labels:
      - "com.example.group=spark"

# Uncomment this if you want to play with spark-connect
#  spark-connect:
#    image: spark-image
#    container_name: spark-connect
#    entrypoint: ['./entrypoint.sh', 'connect']
#    depends_on:
#      - spark-master
#    env_file:
#      - .env.spark
#    volumes:
#      - ./data:/opt/spark/data
#      - ./spark_apps:/opt/spark/apps
#      - spark-logs:/opt/spark/spark-events
#      - ./notebooks:/opt/notebooks
#    ports:
#      - '15000:15000'
#      - '15001:15001'
#      - '15002:15002'

volumes:
  spark-logs:

