# Data Stream Services
EVENTSIM := ./eventsim/startup.sh

# Assuming you have a Makefile with the following content
start:

# Development Targets/ local machine
# -------------------

start-stream-dev: 
	$(EVENTSIM)
