#cloud-config
bootcmd:
- printf "[Resolve]\nDNS=8.8.8.8" > /etc/systemd/resolved.conf
- [systemctl, restart, systemd-resolved]
users:
  - name: root
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCYOecdfndktBBGZbw3fcO1DPNxH+YeW0SRnSNmV6OzCBex6FeLldlcasn6ksc3WIOUN9Gf62e2N1ubbxBBQxFcdYfc7gF/VEwaa7rxZKOi39vcxKKPf4dNTCcA+W7wYGxIWdWFMoNn3MzG/mh+CZ2rTNUK7ricKvifroehH52PZXu6Zzk2nibaJBIDAyVWnp3pNW5rZKZdn/ANNEtDUQl2sTzOaGsG+GC/3KnL77wjBTkYegRjUEpgqK/PgU4dcIe88jW/PyVUT7bIgCvipxU/kS1N9AJjeU9d5oVkmG1/kIg7yx2dux+Qd5LfY+A3cs6n3+yplgeSjGWSQls3z9+wmMw5HdQ2DiAH2d3aBPfjecvXwK/9ndXa1y3Eh3LNCRUZVtvEE8neSnh0ms+3NurmY/xPQpAGAgR+Pzm0SABo6Z6JYOUxKCV5LQqdYirwRHtu8wmn2k894Vsln95h5cJbw9yuWdRc+Ls2rq8nKcCdl7vvwP1cNt8OnmKkrBwZVD8= cody@Buis-Laptop.local

growpart:
    mode: auto
    devices: ["/"]
manage_etc_hosts: localhost
locale: "en_US.UTF-8"
package_update: true
package_upgrade: true
packages:
    - haproxy
runcmd:
- systemctl restart haproxy
- touch /tmp/signal
